### ISSUE TITLE
运行提示TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by sakeri-l** [QiuChenly/QQFlacMusicDownloader#19]
Traceback (most recent call last):
  File "MainServer.py", line 11, in <module>
    from web.API.es import init as es  # 下面无需顺序
  File "D:\QQFlacMusicDownloader\web\API\es.py", line 8, in <module>
    from src.Api.Netease import Netease
  File "D:\QQFlacMusicDownloader\src\Api\Netease.py", line 11, in <module>
    from src.Api.BaseApi import BaseApi
  File "D:\QQFlacMusicDownloader\src\Api\BaseApi.py", line 12, in <module>
    class BaseApi(abc.ABC):
  File "D:\QQFlacMusicDownloader\src\Api\BaseApi.py", line 14, in BaseApi
    def search(self, searchKey: str) -> list[Songs]:
TypeError: 'type' object is not subscriptable

没有看明白这块怎么调用的，不知道是什么错误

**Comment by QiuChenly** [comment]
你好 可以加q看下问题 1925374620

**Comment by sakeri-l** [comment]
早上才看到，已经改好了不对类型做判断就可以我用的python3.7，删除 -> list[Songs]后一切正常，感谢大佬，愉快摸鱼
