### ISSUE TITLE
歌曲名中有特殊字符导致保存失败

### ISSUE THREAD

**Issue by KaiHuaDou** [QiuChenly/QQFlacMusicDownloader#25]
比如说要下载的的`AmaLee - Hacking to the Gate (from "Steins;Gate")`中间出现了`;`和`"`，有可能是这些中断了保存进程。
```log
exception calling callback for <Future at 0x1cc885a5a20 state=finished raised OSError>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "D:\server\paths\QQFlacMusicDownloader\web\App.py", line 87, in done
    ret = ret.result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\server\paths\QQFlacMusicDownloader\src\Common\Tools.py", line 245, in downSingle
    with open(localFile, 'wb') as code:
OSError: [Errno 22] Invalid argument: 'D:\\server\\paths\\QQFlacMusicDownloader/music/AmaLee/AmaLee - Hacking to the Gate (from "Steins;Gate").flac'
```

**Comment by QiuChenly** [comment]
这个问题是因为Windows上的非法文件名导致的。
此问题已被标记但可能短期内不会解决。

**Comment by QingXuDw** [comment]
@KaiHuaDou 我这里做了一些修复的尝试[QingXuDw/QQFlacMusicDownloader](https://github.com/QingXuDw/QQFlacMusicDownloader/tree/main)，你可以试试有没有解决你的问题

**Comment by QiuChenly** [comment]
#30 该问题可能已在此提交中解决，请拉取代码后重新测试。
