### ISSUE TITLE
搜索歌曲 ID 导致程序崩溃

### ISSUE THREAD

**Issue by KaiHuaDou** [QiuChenly/QQFlacMusicDownloader#27]
期望效果：
![image](https://user-images.githubusercontent.com/74781268/224548261-63fd9930-3b55-495f-a9ea-1e12fcdbf745.png)
实际效果：界面无反应，日志如下
```log
127.0.0.1 - - [12/Mar/2023 21:34:38] "OPTIONS /wyy/search/4919447/1/30 HTTP/1.1" 200 -
[2023-03-12 21:34:39,334] ERROR in app: Exception on /wyy/search/4919447/1/30 [GET]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Program Files\Python310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python310\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\server\paths\QQFlacMusicDownloader\web\API\es.py", line 68, in essearch
    lst = netes.searchMusic(
  File "D:\server\paths\QQFlacMusicDownloader\src\Api\Netease.py", line 302, in searchMusic
    for li in result['songs']:
KeyError: 'songs'
127.0.0.1 - - [12/Mar/2023 21:34:39] "GET /wyy/search/4919447/1/30 HTTP/1.1" 500 -
```

**Comment by KaiHuaDou** [comment]
同时，使用`ヒャダインのカカカタ☆カタオモイ-C`也搜索不到这个歌曲

**Comment by QiuChenly** [comment]
你好 这个问题可能是因为日文字体在Windows上的编码出错导致服务器接收到了不可序列化的查询信息。
音乐不支持使用ID搜索，你可以收藏歌曲后在我收藏的音乐中下载。
