### ISSUE TITLE
会出现请求频繁问题

### ISSUE THREAD

**Issue by situchen** [QiuChenly/QQFlacMusicDownloader#7]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 340, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by QiuChenly** [comment]
你好 这个情况可能是因为本机网络或者物理机性能问题导致  我本地电脑并未出现此问题。
我的电脑和网络状态：
1000Mbps 移动
MacBook Pro 16in-ch 2019 / 8core
Base on macOS 13 Ventura

建议的解决方案：
1. 降低多线程数量，如4～ 8线程，如果设为16 或更高线程数量会因为网络带宽不够而导致reset connection，即请求过多无法处理。
